### ISSUE TITLE
Add decorator to allow multiple field validations on same property

### ISSUE THREAD

**Issue by PWKad** [aurelia/validatejs#11]
Should look something like this -
```
@field({ length: { minimum: 3, maximum: 5}, required: true }) firstName = 'Patrick';
```

**Comment by 32graham** [comment]
This seems to already work without the need for `@field`

```js
@length({minimum:3, maximum:5})
@required()
firstName = '';
```
![multiple-validations](https://cloud.githubusercontent.com/assets/821554/15034866/0b4f596c-1240-11e6-93d3-0a7f53744f81.png)

**Comment by PWKad** [comment]
That is really good to hear!  I'm going to go ahead and close this and if in the future someone wants to pass multiple they can re-open this (it shouldn't be too difficult to implement anyway)
