### ISSUE TITLE
ValidateObject bug

### ISSUE THREAD

**Issue by adarshpastakia** [aurelia/validatejs#111]
**I'm submitting a bug report**

* **Library Version:**
major.minor.patch-pre

* **aurelia-framework version:**
1.0.0-rc.1.0.2

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
4.4.5

* **NPM Version:**
3.9.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.39

* **Browser:**
Safari XX

* **Language:**
TypeScript X.X

**Current behavior:**

**Expected/desired behavior:**

 i have created a vaildatemap validation rule which iterates a map and validates each object

```
const validator = new Validator();
validate.validators.map = function(map: Map<string, any>) {
	const errors = []
	map.forEach((v, k) => {
		if (validator.validateObject(v).length > 0) errors.push(k);
	});
	// Unfortunately details are lost, but Aurelia's controller will evaluate and display them on the binding as well.
	// This is only really useful for your `validate()` call when saving.
	return errors.length > 0 ? `${errors.join(',')} has invalid values` : null;
}

function mapRule(config) {
	return new ValidationRule('map', config);
}
export function validatemap(targetOrConfig?, key?, descriptor?) {
	return base(targetOrConfig, key, descriptor, mapRule);
}
```
unfortunately the `validateObject` keeps failing because `propertyName` is null.

* Fix
`validator.js` line 19

```
propertyName = propertyName || ruleInfo.key;
if (propertyName !== null && ruleInfo.key !== propertyName) {
   continue;
}
```

* **What is the expected behavior?**
 it should validate the properties in the map object

* **What is the motivation / use case for changing the behavior?**

**Comment by heruan** [comment]
I confirm, this currently fails:
```javascript
let validator = new Validator();
let foo = { foo: "bar" };
let rules = new ValidationRules().ensure("foo").presence(true);
let errors = validator.validateObject(foo, rules);
console.log(errors);
// results in this ValidationError:
{
    message: "Null can't be blank",
    object: { foo: "bar" },
    propertyName: null,
    rule: {
        name: "presence",
        config: true
    }
}
```
https://github.com/aurelia/validatejs/pull/116 implements @adarshpastakia fix for this.

**Comment by jdanyow** [comment]
closing- validatejs was dropped in last release
