### ISSUE TITLE
TypeScript error: Module ''validate.js'' has no default export

### ISSUE THREAD

**Issue by kristianmandrup** [aurelia/validatejs#112]
**I'm submitting a bug report**

* **Library Version:**
0.7.0

* **aurelia-framework version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.16.41

* **Language:**
TypeScript 2.1-dev

**Current behavior:**

```bash
node_modules/aurelia-validatejs/dist/aurelia-validatejs.d.ts(8,8): error TS1192: Module ''validate.js'' has no default export.
```

Visual Studio code also complains with a red underline under `validate` constant in `import validate from 'validate.js';`

**Expected/desired behavior:**

That it can load `aurelia-validatejs` type definitions without error

**Comment by am2software** [comment]
I have a similar issue also, but with WebPack.  

Running locally is fine, but building for deployment throws an error in WebPack

**Comment by xmichaelx** [comment]
I have similar issue but with [skeleton-typescript-webpack](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack) both locally and deployment. @am2software how did you set it up so you don't get that error on `npm start` ?

**Comment by kristianmandrup** [comment]
I had a similar issue for sortablejs which I solved like this.

`import sortable = require('sortablejs');`

So try:

`import validate = require('validate');`

**Comment by am2software** [comment]
@kristianmandrup that has resolved my issue

in aurelia.validatejs.d.ts change 
`import validate from 'validate.js';`
into
`import validate = require('validate.js');`

**Comment by kristianmandrup** [comment]
Cute ;) I had to do a similar fix for sortable.js, renaming the export variable in the d.ts file

**Comment by xmichaelx** [comment]
Could this fix be included in aurelia.validatejs.d.ts?
