### ISSUE TITLE
Binding behaviour throws error when leaving active shell with validations

### ISSUE THREAD

**Issue by suamikim** [aurelia/validatejs#113]
**I'm submitting a bug report**

* **Library Version:**
0.7.0

* **aurelia-framework version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.2.3

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
JSPM 0.16.19 but not used

* **Browser:**
Chrome 51

* **Language:**
ESNext

**Current behavior:**
I've implemented some validations based on the [latest blog post](http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/) and the [appendant gist](https://gist.run/?id=381fdb1a4b0865a4c25026187db865ce).

The validations are added to a login view which lives inside its own shell. When leaving this shell to the main app shell, the file `validate-binding-behavior.js` throws an error `Cannot read property 'target' of undefined` in line 55.

Do I somehow have to unregister the validations manually or is this a bug?

Here's a runable gist which throws the error when submiting the form: https://gist.run/?id=80e8325e62a7502e5a54e5c148e8c011

**Comment by jdanyow** [comment]
try running `this.controller.reset()` before switching the app root.

updated validation gist with new bits: https://gist.run/?id=3625244afe4f188785190b23f2e7f472
