### ISSUE TITLE
several rules unnecessarily insert 'true' if no other argument

### ISSUE THREAD

**Issue by gravsten** [aurelia/validatejs#118]
These rules are: **date**, **datetime**, **email**, **numericality**, **presence**, **url**.

For example:
```
ValidationRule.presence = function presence() {
      var config = arguments.length <= 0 || arguments[0] === undefined ? true : arguments[0];

      return new ValidationRule('presence', config);
    };
```

This doesn't seem to be based on any special handling in these rules, and thus may probably be changed to:
```
ValidationRule.presence = function presence(config) {
      return new ValidationRule('presence', config);
    };
```

As a result, '@require' would result in config being undefined... without any side effect.

**Comment by jdanyow** [comment]
closing- validatejs was dropped in last release
