### ISSUE TITLE
Duplicate ValidationError

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/validatejs#14]
The ValidationError class is duplicated in both valiatejs and validation. We should remove it from validatejs and just have a single version in validation since it's part of the ValidationReporter interface.

**Comment by PWKad** [comment]
@EisenbergEffect  Any thoughts on how to handle the constructor here?  Should the library be required to manipulate the validation result to match before instantiating a new `ValidationError` or some other way of manipulating the data?

For instance in validatejs the constructor takes in the error format specific to validatejs and transforms it in to the proper properties and then assigns it.  We could move this to validatejs only and have the constructor be simply `Object.assign(this, data)` or something else if there is a better idea.

**Comment by EisenbergEffect** [comment]
I think we need the stadard error "shape" so that the validate behavior and renderers can work independently of the validation library driving the messages. We don't necessarily need the class at all. It could be an interface defined in the validation library. Then, validatejs can instantiate objects that match that shape in whatever way is most convenient for it. Does that answer the question?

**Comment by PWKad** [comment]
Yes I'm about to push up just using a constructor and expecting the error to already match that class for now and we can evaluate further if there is even a better approach (at least it closes this one for now)
