### ISSUE TITLE
reduce duplication in fluent api

### ISSUE THREAD

**Issue by mbroadst** [aurelia/validatejs#17]
Hey guys, not sure how much refactoring this would involve, but I think if your injected validator was a factory we would end up with a much nicer api:

```
  this.validator = validator(this.model)
    .ensure('firstName').required().length({minimum: 3, maximum: 10})
    .ensure('lastName').required();
```

reducing duplication of having to specify `this.model` in every ensure.

**Comment by PWKad** [comment]
I'm open to the most simple implementation - do you think with this we could still apply validation rules to multiple objects if needed for some reason?

**Comment by mbroadst** [comment]
@PWKad I was operating under this current assumption: https://github.com/aurelia/validatejs/blob/master/src/validator.js#L33

However, if you returned a factory then yes you'd be able to use that factory method multiple times to create validators for different objects - I'm not quite sure how you'd do that with the current approach so this might actually be the most compelling point for my proposal.

**Comment by PWKad** [comment]
Oh good point.  I forgot I put that check in there :)  I'm down for this can we get a few +1's from some of the other early adopters?  I wish there was a nice way to poll and get concensus on stuff like this :)

**Comment by mbroadst** [comment]
well there's my vote 😄

**Comment by apawsey** [comment]
vote from me

**Comment by PWKad** [comment]
@mbroadst @apawsey  what about this - 

```
import {Validator} from 'aurelia-validatejs';

export class MyViewModel {
  constructor() {
    let obj = { firstName: '' };
    this.validator = new Validator(obj)
      .ensure('firstName')
        .required();
  }
  submit() {
    this.validator.validate();
  } 
}
```

**Comment by EisenbergEffect** [comment]
It seems that it would be nice to have the rules separated from an instance but then be able to apply them later. Why not this?

```
import {Validator} from 'aurelia-validatejs';

export class MyViewModel {
  constructor() {
    let obj = { firstName: '' };
    this.validator = new Validator()
      .ensure('firstName')
        .required()
      .bindTo(obj);
  }
  submit() {
    this.validator.validate();
  } 
}
```

You could set the rules up and then simply bind them to instances. This would return a bound validator that can independently validate the provided object.

**Comment by PWKad** [comment]
Currently everything is built around the idea that the config is specific to an instance so you need the instance to interact with the config to do things such as add rules.  We can probably clean up the API first and look at re-using sets of rules down the road.  The easiest way to accomplish what you are showing above would be to simply create a function for adding validation rules to an obj - 

```
let obj = { name: '' };
this.validator = reuseValidation(obj);

function reuseValidation(obj) {
  return new Validator(obj)
    .ensure('name')
      .required();
}
```

**Comment by EisenbergEffect** [comment]
That seems like a simple solution :)

**Comment by mbroadst** [comment]
@EisenbergEffect I had proposed what I think ultimately is the most flexible solution: 

```
validator = injectedValidator
  .ensure('firstName').length({ minimum: 3 }).required()
  .ensure('lastName').length({ maximum: 5}).presence().required();

...snip...

validator.validate(obj);        
```

where the validator essentially becomes a rule set which could "notify" and subscribed reporter and thus has nothing to do with the data itself. I appreciate that this would require basically a complete overhaul of the existing code, but I figured I'd get the ideas of paper while the discussion is ongoing

**Comment by PWKad** [comment]
For now let's stick with your original suggestion to reduce the API.  Creating re-usable rulesets should still be trivial but I don't want to re-write everything from scratch yet because I still don't think there is a very common use-case for re-using the rule set across models (classes, whatever) as it's completely tied to that model (class) anyway.  If the property names are shared across models it should be super easy to create a function that decorates the instance like shown above.

**Comment by mbroadst** [comment]
Sounds reasonable to me
