### ISSUE TITLE
Adding decorators results in an exception

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/validatejs#22]
Adding a `required` decorator on a view model property results in an exception

```
export class EditStable{
	reporter: any;

        constructor() {
               this.reporter = ValidationEngine.getValidationReporter(this.stable);
        }

	@required
	Name: string = "";
}
```
```
aurelia-logging-console.js:86 ERROR [app-router] Error: TypeError: Cannot read property 'initializer' of undefined
	    at deco (http://localhost:1506/jspm_packages/npm/aurelia-validatejs@0.2.0/base-decorator.js:16:22)
	    at base (http://localhost:1506/jspm_packages/npm/aurelia-validatejs@0.2.0/base-decorator.js:40:14)
	    at required (http://localhost:1506/jspm_packages/npm/aurelia-validatejs@0.2.0/decorators.js:24:36)
	    at __decorate (http://localhost:1506/app/views/editStable.js:7:114)
	    at execute (http://localhost:1506/app/views/editStable.js:92:13)
	Error loading http://localhost:1506/app/views/editStable.js
```

I'm transpiling TS into es6 with module type `system`

**Comment by EisenbergEffect** [comment]
@PWKad This is likely a difference in the way that TS transpiles and handle property descriptors vs. Babel.

**Comment by EisenbergEffect** [comment]
Actually, I don't think that TS always provides the property descriptor. That's probably the issue. If one isn't provided your going to need to handle that situation.

**Comment by EisenbergEffect** [comment]
(Strictly thinking I think this is non-spec compliance on the TS part most likely, but we need to handle it unfortunately.)

**Comment by MaximBalaganskiy** [comment]
>  I don't think that TS always provides the property descriptor
That's exactly what happens. It only gives a descriptor for properties

**Comment by EisenbergEffect** [comment]
Right. Even though the spec is changing. In the old spec, I believe there should alway be a descriptor in this case. So, TS is probably fudging it a little bit. We can fix our implementation to account for it though.

**Comment by MaximBalaganskiy** [comment]
:+1:

**Comment by searus** [comment]
Is there a workaround for this?

**Comment by PWKad** [comment]
Does this seem like it would appropriately handle the situation - 

https://github.com/aurelia/binding/blob/master/src/decorator-observable.js#L8-L20

Basically if it isn't babel just make the `descriptor` an object?

**Comment by searus** [comment]
just tested applying that logic into validatejs/base-decorator and it solved the problem for me

**Comment by EisenbergEffect** [comment]
yes

**Comment by PWKad** [comment]
I'm not sure the best way to represent this in a unit test but I pushed out a fix.  @searus can you double-check and make sure that commit looks the exact same way when you implemented it?  Thanks!

**Comment by searus** [comment]
Looks identical to what I have - except you have nice comments :+1:
