### ISSUE TITLE
Sample app does not run after following instructions

### ISSUE THREAD

**Issue by stevies** [aurelia/validatejs#24]
The sample app does not run after following the instructions.  There is no `gulp start` - I used `gulp serve` . The version of font-awesome referenced in index.html is wrong.  Fixed that, but the app cannot find `dist/main.js` - it does not appear to be getting built anywhere.  Maybe it does work, but then the instructions need to be clearer.

>http://localhost:3001/dist/main.js Failed to load resource: the server responded with a status of 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:3001/dist/main.js
	Error loading http://localhost:3001/dist/main.js
>

**Comment by stevies** [comment]
Ah - there is a `gulp build-sample` - ran that, built the `dist/main.js` - app still fails to start, can't find `aurelia-validation@0.7.0.js`

>Failed to load resource: the server responded with a status of 404 (Not Found)
undefined:1 Uncaught (in promise) Error: Error: XHR error (404 Not Found) loading http://localhost:3001/jspm_packages/npm/aurelia-validation@0.7.0.js(…)
http://localhost:3001/jspm_packages/npm/aurelia-validation@0.7.0.js Failed to load resource: the server responded with a status of 404 (Not Found)

Getting closer...

**Comment by stevies** [comment]
Duplicate of #20

**Comment by PWKad** [comment]
https://github.com/aurelia/validatejs/commit/c77f3693587a607393e73a90f01f5c39f53084f6

**Comment by PWKad** [comment]
I'll keep that other issue open until it is fixed my bust
