### ISSUE TITLE
Consider 'computedFrom' support

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/validatejs#28]
It would be nice to have. I could work around it by triggering validation in `passes` analog if it existed

**Comment by PWKad** [comment]
What is `computedFrom`?  Does `equality` not cover this?

**Comment by MaximBalaganskiy** [comment]
It does for password and confirmation, but more complex scenarios may require triggering validation on other fields. Let's say you picked a state and depending on that your prices might become invalid...

**Comment by PWKad** [comment]
All of the relevant rules are re-evaluated upon validating the object so this shouldn't be needed.
