### ISSUE TITLE
Consider `debounce` decorator/fluent call

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aurelia/validatejs#30]
To further support validations with api calls we need to delay the check

**Comment by MaximBalaganskiy** [comment]
In the light of the #23 discussion this could be the configuration in HTML. There is already debounce behavior.

**Comment by PWKad** [comment]
This should be supported currently if you used `debounce` because the setter would never be triggered until the debounce occurs so this should be working already.

**Comment by jdanyow** [comment]
right- you can use `& debounce` in conjunction with `& validate`
