### ISSUE TITLE
Typescript decorators do not work

### ISSUE THREAD

**Issue by searus** [aurelia/validatejs#31]
When using TypeScript and the decorator syntax for validatejs, the validation does not occur.
I am assuming that it is something to do with the way that TypeScript generates the decorator code.

I will try and put together a small demo, but I'm really tight for time right now.  To move on, I have switched to the fluent syntax which works fine in TypeScript.

**Comment by searus** [comment]
I have created a quick demo here: https://github.com/reyno-uk/aurelia-validatejs

**Comment by PWKad** [comment]
Thanks I think this issue is related and the fix is there just not released - if that wasn't fixing it and there is something else I'll make sure we get this in the next release.  If it is a dupe let me know.  I'll run the repro this weekend to verify if I've not heard anything.

**Comment by searus** [comment]
@PWKad I don't think this is fixed with issue #22.  I get the problem with that fix applied in base-decorator.js

**Comment by jdanyow** [comment]
this is fixed in the alpha release http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/
