### ISSUE TITLE
Start full documentation for the library

### ISSUE THREAD

**Issue by apawsey** [aurelia/validatejs#42]
Rather than just updating the readme, we need to start fully documenting the behaviour etc.  Is there a template, folder, repository... what's the instructions to start contributing?

(There was a lot of moaning on gitter today, regarding aurelia's docs, so let's start to move it forward)

**Comment by EisenbergEffect** [comment]
To create documentation, simply start by writing a markdown file. Once that matures, we can convert it quickly into our docs format, drop it in the right location and then publish it to the official docs. We can turn that around pretty quick once the core content is created.

**Comment by PWKad** [comment]
Plugins are not currently imported in to the docs - is that changing?  If not probably makes more sense to start PR'ing the `docs` folder with standard markdown.

**Comment by EisenbergEffect** [comment]
We can add plugin docs. We have fetch now. We just need the docs (articles and apis) in the right format.

**Comment by PWKad** [comment]
👍

**Comment by jdanyow** [comment]
docs have been added
