### ISSUE TITLE
errors with .d.ts files

### ISSUE THREAD

**Issue by lucamorelli** [aurelia/validatejs#51]
Hi, I just added the library in a vs project with typescript and when I try to compile I have these errors.

```
...\jspm_packages\npm\aurelia-validatejs@0.3.0\aurelia-validatejs.d.ts(7,10): error TS2307: Build: Cannot find module 'aurelia-validation'.
...\jspm_packages\npm\aurelia-validatejs@0.3.0\aurelia-validatejs.d.ts(14,24): error TS2307: Build: Cannot find module 'validate.js'.

```
am I missing something?

**Comment by PWKad** [comment]
Already tracking adding types in this issue - https://github.com/aurelia/validatejs/issues/10

Contributions to add types welcome :)
