### ISSUE TITLE
Plugin questions

### ISSUE THREAD

**Issue by Vizer** [aurelia/validatejs#53]
Hi guys,
I am investigating this plugin and currently I have several questions:
- Can I set custom message with decorator rule?
- If validation rules were specified with decorators how can I trigger validation on form submit?
- How can I set field as invalid programmatically?
- Is it any workaround for already known [issue](https://github.com/aurelia/validatejs/issues/39)
- When fix for [this](https://github.com/aurelia/validatejs/issues/48) issue will be released?
- When custom validation rules will be available?

**Comment by Vizer** [comment]
@PWKad, @EisenbergEffect, could you provide some information regarding my questions?

**Comment by EisenbergEffect** [comment]
You'll just have to be patient. The validatejs library is in a very early stage, still undergoing significant changes, refactorings and feature work. As stated in the announcement blog post, the current releases are made for people who want to provide early feedback and assistance with design and implementation, not so much for people who want to use it for normal development just yet.

**Comment by Vizer** [comment]
@EisenbergEffect, could you provide some approximate date when it is going to be ready for normal development?

**Comment by EisenbergEffect** [comment]
Not at this time.

**Comment by Vizer** [comment]
@EisenbergEffect, this is very important for my current project. I really depend on this plugin because validation is big and important part of project's functionality. In this case whole aurelia infrastructure is not ready for normal development.

**Comment by EisenbergEffect** [comment]
There is nothing stopping you from using whatever validation library and strategy you want. Many members of the community have built their own solutions without much effort.

We're sorry the feature you want isn't ready yet. This is open source and the reason we have made this available in the early state is to solicit feedback and contributions. You are always welcome to help out in the development effort, which is the spirit of open source.

**Comment by njappboy** [comment]
@EisenbergEffect Hey Rob, @Vizer, is a developer on my team. We were looking at using valdiatejs instead of @jdanyow [aurelia-validation](http://aurelia.io/validation/).  Do you have any other references to community member implementations? 

Is this type of implementation the community is using for their own solutions? : http://stackoverflow.com/questions/35624771/aurelia-validating-form-with-reusable-validatable-custom-element

**Comment by EisenbergEffect** [comment]
A couple of others have comments on other issues here about custom validation solutions they have built. I think there are some links around. Definitely, we want to have a solid default option...we just are still a few weeks out from having it ready for more broad consumption. This library is more for early adopters and those who want to get involved

**Comment by njappboy** [comment]
Understood, and thank you for the respond. 
Sorry for the negative tone/language in Vizer's comments. His comment seems unprofessional and counter-productive, imho.

**Comment by DimaSemchuk** [comment]
@EisenbergEffect considering conversation above, if I wan't to pick a framework as a foundation for front end of my project, can you advice if I may use aurelia at this stage, or should I wait till several things are fixed?

**Comment by EisenbergEffect** [comment]
@DimaSemchuk Yes, it's solid as a foundation for building apps. The community (as well as our core team) have been using it for many months, including putting apps in production. In this issues, we are only talking about an optional validation plugin. There are other options for validation and it's possible to build your own as well. This particular plugin is a little less mature at this time, but is moving quickly. But remember, Aurelia is a modular framework, so you can pick and choose what you want, use our plugins or community addons as well as build your own.
