### ISSUE TITLE
@required decorator does appear to work

### ISSUE THREAD

**Issue by mttmccb** [aurelia/validatejs#54]
I've tried clear the text field, not setting it in the model in the first place but I never received a warning about a required field. Am I missing something obvious?

**Comment by PWKad** [comment]
If the property doesn't exist validatejs thinks it was an error on your part I believe and reports out nothing.

**Comment by mttmccb** [comment]
But it does exist, it's in the model I'm using.

The fluent syntax worked with the same model but the decorator didn't.

**Comment by mttmccb** [comment]
I'll try with a gist.run and post it here if it breaks or not

**Comment by PWKad** [comment]
Throw together a repro and we can look at it

**Comment by mttmccb** [comment]
I've downloaded the latest (webpack ES2016) skeleton and added the bits needed for aurelia-validatejs and copied in the views from the sample folder in this [aurelia-validatejs-decorators repo](https://github.com/mttmccb/aurelia-validatejs-decorators).

@required doesn't seem to work but the fluent one does.

**Comment by PWKad** [comment]
Sounds correct as you mentioned the other is a duplicate sorry I missed this earlier

**Comment by jdanyow** [comment]
this is fixed in the latest build
