### ISSUE TITLE
Validation Decorator - Property Rewrite

### ISSUE THREAD

**Issue by ppn2** [aurelia/validatejs#55]
Can we please avoid property rewrite. I don't think it is good idea to touch the model objects in general. In our case, in some of the properties we have getter and setters and aurelia is breaking them when validation decorator is defined on them.

**Comment by EisenbergEffect** [comment]
@PWKad Didn't we recently discuss removing the property re-writing in favor of leeting that all be handled by the validate binding behavior?

**Comment by PWKad** [comment]
Duplicate of https://github.com/aurelia/validatejs/issues/21
