### ISSUE TITLE
Plugin configuration works ?

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/validatejs#62]
Any working example how to configure the `aurelia-validatejs`, to replace the default ValidationRenderer ? 

The  `.plugin('aurelia-validatejs', (config) => {console.log('::', config)});` does not invoke the configuration,  `import {ValidationConfig} from 'aurelia-validatejs'` is `undefined` and folowing test prints `udefined`
```javascript
this.validator = new Validator(this.model);
console.log('::', this.validator.config);
```
 Any help/hint/example highly appreciated.

**Comment by PWKad** [comment]
Duplicate / tracking - https://github.com/aurelia/validatejs/issues/2
