### ISSUE TITLE
How to handle properties with different labels

### ISSUE THREAD

**Issue by jadrake75** [aurelia/validatejs#66]
If you model has a property like "price" but this is rendering in the UI using a label like "Total Purchase" when it validates you will get messages referring to "Price".  Now I know I can set message, but his seems to only be the message part "after" the variable.  ie. if I set a message like "Total purchase must be a number greater than 0" I will get "Price Total purhase must be a number greater than 0"

![purchase-dialog](https://cloud.githubusercontent.com/assets/3221886/15439876/5cb7d718-1ea0-11e6-8b8e-7cf354f04ac9.png)

I am assuming this is a simple option I am missing but I have not located anything.

**Comment by apawsey** [comment]
This is a validate.js option.  By default it uses the name of the property.  If you pass a config for that property, including a message, prefix the message with ^ to avoid it adding the property name.

eg:
```
new Validator(this)
    .ensure('price')
        .required({message: '^Total purchase doesn't look like a number!  Think you ought to check that buddy'});
```

**Comment by jadrake75** [comment]
ah... yes... I guess if I put on my regexy hat that makes sense.  I saw that in a few examples but it didn't click.  ok.... lets close it out!
