### ISSUE TITLE
Sample app is broken

### ISSUE THREAD

**Issue by RobertHerhold** [aurelia/validatejs#75]
If you load up the sample and click Submit on the decorators page, it will submit successfully. As soon as you change something (i.e. delete a character from the first name) the errors will appear and pressing submit will yield an alert saying that there are errors. However, if you change nothing, then the submit button will say there are no errors, even though several of the fields shouldn't be passing the validation.

**Comment by jdanyow** [comment]
sample app was deleted- use the gist in the blog post instead: http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/
