### ISSUE TITLE
getContextFor is missing in aurelia-binding.d.ts

### ISSUE THREAD

**Issue by jdanyow** [aurelia/validatejs#76]
@Opiskull commented on [Thu Jun 02 2016](https://github.com/aurelia/binding/issues/422)

Hi,

I tried the aurelia-validatejs package yesterday within a typescript project and it doesn't find the getContextFor function in the typescript definition. So adding this function to `aurelia-binding.d.ts` should fix that problem.

---

@jdanyow commented on [Thu Jun 02 2016](https://github.com/aurelia/binding/issues/422#issuecomment-223464519)

need to fix this in the validatejs package.  this is an internal API we don't need to expose

**Comment by Opiskull** [comment]
Ah.. sry about that... I thought it needs to be fixed in aurelia/binding :)

**Comment by jdanyow** [comment]
no worries

**Comment by jdanyow** [comment]
d.ts issues have been resolved
