### ISSUE TITLE
Latest commit has overwritten changes in validatejs.d.ts

### ISSUE THREAD

**Issue by searus** [aurelia/validatejs#80]
@PWKad @EisenbergEffect the changes that were merged in from my pull request (#64) have been overwritten by the commit "chore(all): prepare release 0.4.0".

Was that intentional?

**Comment by EisenbergEffect** [comment]
The d.ts files are generated from the source. To fix issues with typings, they have to be fixed in the source. @PWKad may not have been aware of that or accidentally missed that your PR was against the d.ts and not the source.
