### ISSUE TITLE
Documentation desperately required re custom validation rules and async validation

### ISSUE THREAD

**Issue by jsobell** [aurelia/validatejs#81]
Since there's no indication of the relationship between validate.js and the library, can we have an example showing:
- a custom validation rule
- an async validation rule
This will help adoption and feedback processes.
I assume these are being passed to the validate.js because there's no sign of any rule definitions in the aurelia-validat* source.

**Comment by richardbartley** [comment]
Yes, is it possible and can we have some document guidance on how to create and call expensive rules i.e. ones that call out to a service / database call.  Perhaps in the registration example, show how to do a lookup to check if the email address is already registered?

**Comment by EisenbergEffect** [comment]
I believe that discussion in other issues is bearing out the design of the apis for these scenarios currently so I'm closing this as a duplicate, more or less.
