### ISSUE TITLE
Is it possible to prioritise validation rules and cancel the validation of expensive rules?

### ISSUE THREAD

**Issue by richardbartley** [aurelia/validatejs#83]
There are simple rules, i.e. required, max length, etc and these are cheap to validate.  If there is an expensive service / database validation rule, can we prioritise the rules and defer execution of the expensive rule until the simple ones pass ok?

**Comment by EisenbergEffect** [comment]
@jdanyow Can this be closed as a duplicate since there's heavy discussion on async rules in other issues?

**Comment by jdanyow** [comment]
I was keeping it open as a reference/reminder

**Comment by jdanyow** [comment]
Issue moved to [aurelia/validation #289](https://github.com/aurelia/validation/issues/289) via [**ZenHub**](https://www.zenhub.com/)
