### ISSUE TITLE
 Cannot set property 'configurable' of undefined

### ISSUE THREAD

**Issue by Ma3yTa** [aurelia/validatejs#84]
After updating aurelia-validatejs I got error `` undefined:1 Uncaught (in promise) Error: Cannot set property 'configurable' of undefined `` https://gyazo.com/a60d0c503bbad66d8e8e4050b65dfefd

its the decorator that fails when adding the rule:
```

 function addRule(target, key, descriptor, targetOrConfig, rule) {
    var rules = _aureliaMetadata.metadata.getOrCreateOwn(metadataKey, ValidationRules, target);
    if (targetOrConfig === null || targetOrConfig === undefined) {
      targetOrConfig = true;
    }
    rules.addRule(key, rule(targetOrConfig));

    descriptor.configurable = true;   <---------------- fails here
  }
```

The descriptor is ``undefined``

**Comment by Ma3yTa** [comment]
@PWKad or @jdanyow Could you please take a look?

**Comment by imressed** [comment]
Have the same error...
