### ISSUE TITLE
TypeScript: Cannot find module validate.js

### ISSUE THREAD

**Issue by genericuser-me** [aurelia/validatejs#91]
Hi,

I am getting the following error while running the application.

ERROR in C:\prj\Project\MyApp\node_modules\aurelia-validatejs\dist\aurelia-validatejs.d.ts
(8,22): error TS2307: Cannot find module 'validate.js'.

Can anyone please help?

**Comment by jasoncarreira** [comment]
Comment out 
```import validate from 'validate.js';```
in the aurelia-validatejs.d.ts

**Comment by WorldMaker** [comment]
A workaround for now:

```
typings install -SG github:aurelia/validatejs/lib/validatejs.d.ts#4b9a5291dd02b13b37dad232f2731a85ad1422a2
```

(Or, noImplicitAny fixed: `typings install -SG github:aurelia/validatejs/lib/validatejs.d.ts#9e27614514df9ada912a07346347f20a0ce6e26d`)

**Comment by jdanyow** [comment]
validate.js was dropped in the last release
