### ISSUE TITLE
Validate complex entities

### ISSUE THREAD

**Issue by jods4** [aurelia/validatejs#95]
This is a spin-off of aurelia/validation#252 to answer @adarshpastakia who asked how to validate a `Hotel` that has a Map of `HotelLanguage`.

I haven't actually built the code, but I would use something like this: 
```typescript
// 1. Build a custom validator for validatejs. It validates all values of a Map
import { Validator } from 'aurelia-validatejs';
const validator = new Validator() // ugly... or DI

validate.validators.map = function(value: Map) {
  const hasErrors = map.values().some(v => validator.validateObject(v).length > 0);
  // Unfortunately details are lost, but Aurelia's controller will evaluate and display them on the binding as well.
  // This is only really useful for your `validate()` call when saving.
  return hasErrors ? "has invalid values" : null; 
}

// 2. If you want to make it useable with a decorator
import { base, ValidationRule } from 'aurelia-validatejs';

const mapRule = new ValidationRule('map', true);

export function validateValues(targetOrConfig, key, descriptor) {
  return base(targetOrConfig, key, descriptor, mapRule, true);
}

// 3. Now you should be able to do so:
class Hotel {
  @validateValues
  languages: Map<string, HotelLanguages>;
}
```

@jdanyow 
Writing this code has shown me a few things: it is cumbersome to write your own validators.
Suggestions:
- export a simple function to get or set constraints/metadata `getRules(object)`.
- drop the custom metadata format `ValidationRule`. In the code above I had to do a little dance around `Validator` because the stored rules are not in the native `validatejs` format. Is there any reason not to store plain constraints? It would make things easier and this module is specific to `validatejs` anyway, it's not generic.
- declaring a new decorator is not very intuitive. This is rather minor, it's probably just a matter of naming `base` something else. Or maybe we could not export `base`, because with the changes suggested above I think the following code is decent:
```typescript
export function validateValues(target, key) {
  getRules(target)[key] = true;
}
```

**Comment by jsobell** [comment]
Can I suggest that we don't spin off this thread just yet? We desperately need to get the core functionality nailed down, and if there is a generic requirement for a feature then we need to incorporate or support that in the core system, so discussing options or solutions outside of that will fragment the process of finding a solution.
Just a friendly suggestion...

**Comment by adarshpastakia** [comment]
@jods4 thanks for the example, will give it try and keep you posted

**Comment by adarshpastakia** [comment]
@jods4 @jdanyow i managed to add the map validator made a slight change to the code, however i faced a couple of issues 

```js
const validator = new Validator();
validate.validators.map = function(map: Map<string, any>) {
  const errors = []
  map.forEach((v, k) => {
    console.log(v, validator.validateObject(v));
    if (validator.validateObject(v).length > 0) errors.push(k);
  });
  // Unfortunately details are lost, but Aurelia's controller will evaluate and display them on the binding as well.
  // This is only really useful for your `validate()` call when saving.
  return errors.length > 0 ? `${errors.join(',')} has invalid values` : null;
}

function mapRule(config) {
  return new ValidationRule('map', config);
}
export function validatemap(targetOrConfig?, key?, descriptor?) {
  return base(targetOrConfig, key, descriptor, mapRule);
}
```

* it wouldn't validate the map object unless i add `& validate` to the property
```html
  <ui-language languages.bind="model.languages & validate" select.trigger="changeLanguage($event)" add.trigger="addLanguage($event)" delete.trigger="removeLanguage($event)">Language</ui-language>
```

* unfortunately the validateObject did not work, i keep getting this error even if the object was valid, it doesn't seem to pick the property name, so even when the map object is valid i still get back an error. the property in this case is `description`
```
{rule: ValidationRule, message: "Null can't be blank", object: HotelLanguage, propertyName: null}
```

**Comment by jods4** [comment]
> it wouldn't validate the map object unless i add  & validate  to the property

Right... :disappointed: This is a limitation of the current `aurelia-validation` API. Only properties linked to UI bindings are validated. I think @jdanyow wants to add a `.validate(object)` API to make sure _every_ property of the object gets validated. 

> i keep getting this error even if the object was valid, it doesn't seem to pick the property name

Really not sure about this one, sorry. You'll have to debug it to find out where it goes wrong :frowning:

**Comment by jdanyow** [comment]
closing- we have a new release that supports some or possibly all of this stuff. please open an issue in aurelia-validation for anything that's missing
