### ISSUE TITLE
Feature request: subproperty validation

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/validatejs#98]
I pull in some entities through breeze that have navigation properties, and I need to validate properties on the navigation property. So it would help me big time if this could be supported:
```
    ValidationRules
    .ensure('user.lastName').required()
    .on(this);
``` 

https://gist.run/?id=8ead16d0aa96a1c59b14eecbc59538fd

**Comment by devanp92** [comment]
@JeroenVinke I found this to work (https://gist.run/?id=89fd2c2e4ddc195c19f5717920312a2f).

```
ValidationRules
.ensure('lastName')
.required()
.on(this.user);
```


Since ```ensure``` requires a property of an object, make the validation rules check ```this.obj``` (```this.user``` in your case). Not sure if this is the correct way - but might be a workaround.

**Comment by JeroenVinke** [comment]
@devanp92 Thanks, I'm aware of that, but this feature request is mainly for doing things like this:

```
    ValidationRules
    .ensure('password.original').required()
    .ensure('lastName').required()
    .on(this.user);
```

where one property exists directly on the object and one property exists in a subproperty

**Comment by devanp92** [comment]
@JeroenVinke Gotcha. That sounds like a useful feature to add! :+1:

**Comment by bobpardoe** [comment]
Any idea when this might be available? I want to start using the spoonx orm but I can't until model.property works for the ValidationRules

**Comment by jdanyow** [comment]
main repo has same issue
